var searchData=
[
  ['callback_20resource_20safety_0',['Callback Resource Safety',['../md_usage.html#autotoc_md65',1,'']]],
  ['callback_5fdescriptor_5ft_1',['callback_descriptor_t',['../namespaceopenpresso.html#a753f1aab2c6b7b78f2d93158960e2736',1,'openpresso']]],
  ['callback_5ft_2',['callback_t',['../classopenpresso_1_1interfaces_1_1_brew_profiler.html#a8848d9d029a691c02d33d51c87c8c6c1',1,'openpresso::interfaces::BrewProfiler::callback_t'],['../classopenpresso_1_1interfaces_1_1_logical_input.html#ab4d42ecc667875da4e5e6f386395af04',1,'openpresso::interfaces::LogicalInput::callback_t'],['../classopenpresso_1_1interfaces_1_1_pressure_sensor.html#a36e79aa06f87ce4308d5dceac8d9b281',1,'openpresso::interfaces::PressureSensor::callback_t'],['../classopenpresso_1_1interfaces_1_1_temperature_sensor.html#a8868739392b6698949376085fd6764b7',1,'openpresso::interfaces::TemperatureSensor::callback_t'],['../classopenpresso_1_1interfaces_1_1_weight_sensor.html#ab555286fcd39b7223e916af7d7b8862e',1,'openpresso::interfaces::WeightSensor::callback_t']]],
  ['callbacks_20unregister_3',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['chip_4',['chip',['../structopenpresso_1_1_pin_addr.html#aea5d0bcc18240918911eaa57bb31cc83',1,'openpresso::PinAddr']]],
  ['cleanup_5',['Automatic Cleanup',['../md_usage.html#autotoc_md61',1,'']]],
  ['cmake_20config_20and_20build_6',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['cmake_20fetchcontent_7',['CMake FetchContent',['../md_installation.html#install-cmake-fetchcontent',1,'']]],
  ['cmake_20fetchcontent_20simplest_8',['Option 2: CMake FetchContent (Simplest)',['../md_quick__start.html#autotoc_md13',1,'']]],
  ['cmake_20subdirectory_9',['CMake subdirectory',['../md_installation.html#install-cmake-subdirectory',1,'']]],
  ['cmake_20toolchain_20from_20conan_20profile_10',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['compensation_11',['Feedforward Terms (Brewing Compensation)',['../pid_tuning.html#autotoc_md78',1,'']]],
  ['compilation_12',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['compiling_13',['Cross-Compiling',['../md_crosscompiling.html',1,'']]],
  ['complete_20example_14',['Complete Example',['../device_config.html#autotoc_md54',1,'']]],
  ['component_20access_15',['OpenpressoCore &amp;amp; Component Access',['../md_usage.html#autotoc_md58',1,'']]],
  ['component_20access_3a_16',['Component Access:',['../classopenpresso_1_1interfaces_1_1_openpresso_core.html#autotoc_md2',1,'']]],
  ['component_20overview_17',['Component overview',['../device_config.html#autotoc_md36',1,'']]],
  ['component_5fconfig_2ehpp_18',['component_config.hpp',['../component__config_8hpp.html',1,'']]],
  ['component_5fconfig_5ft_19',['component_config_t',['../namespaceopenpresso.html#a85e8f6f3600a2b8dcc52cd9d27c28e07',1,'openpresso']]],
  ['component_5flabel_5ft_20',['component_label_t',['../namespaceopenpresso.html#a188738323c067c1fe93dbf40422b89e7',1,'openpresso']]],
  ['components_21',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['components_22',['components',['../structopenpresso_1_1_device_config.html#a81313de39e44fe7103a94f572cf61551',1,'openpresso::DeviceConfig']]],
  ['components_20dependencies_3a_23',['Components dependencies:',['../structopenpresso_1_1_device_config.html#autotoc_md1',1,'']]],
  ['components_20map_24',['The Components Map',['../device_config.html#autotoc_md32',1,'']]],
  ['components_5fmap_5ft_25',['components_map_t',['../namespaceopenpresso.html#a14f390a5a1ff2e94a1fc0f4bc8a54921',1,'openpresso']]],
  ['conan_20package_20preferred_26',['Conan package (preferred)',['../md_installation.html#install-with-conan',1,'']]],
  ['conan_20profile_27',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['conan_20recommended_28',['Option 1: Conan (Recommended)',['../md_quick__start.html#autotoc_md12',1,'']]],
  ['config_20and_20build_29',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['config_2ehpp_30',['config.hpp',['../config_8hpp.html',1,'']]],
  ['configuration_31',['Configuration',['../device_config.html',1,'Device Configuration'],['../device_config.html#autotoc_md52',1,'Watchdog Configuration']]],
  ['configuration_20parameters_32',['Configuration Parameters',['../pid_tuning.html#autotoc_md75',1,'Configuration Parameters'],['../md_flow__sensor__tuning.html#autotoc_md86',1,'Configuration Parameters']]],
  ['configure_20components_33',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['constantflow_34',['ConstantFlow',['../structopenpresso_1_1brew__step__targets_1_1_constant_flow.html',1,'openpresso::brew_step_targets']]],
  ['constantpressure_35',['ConstantPressure',['../structopenpresso_1_1brew__step__targets_1_1_constant_pressure.html',1,'openpresso::brew_step_targets']]],
  ['containers_36',['Using prebuilt containers',['../md_crosscompiling.html#autotoc_md96',1,'']]],
  ['controller_20architecture_37',['Controller Architecture',['../md_usage.html#autotoc_md70',1,'']]],
  ['controller_5fbase_2ehpp_38',['controller_base.hpp',['../controller__base_8hpp.html',1,'']]],
  ['controllerbase_39',['ControllerBase',['../classopenpresso_1_1interfaces_1_1_controller_base.html',1,'openpresso::interfaces']]],
  ['controllers_40',['Controllers',['../device_config.html#autotoc_md41',1,'Controllers'],['../md_usage.html#autotoc_md69',1,'Controllers']]],
  ['controllers_20deactivation_20and_20sensors_20callbacks_20unregister_41',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['core_42',['2. Initialize Core',['../md_quick__start.html#autotoc_md17',1,'']]],
  ['core_20destruction_43',['Safe Core Destruction',['../md_usage.html#autotoc_md64',1,'']]],
  ['creation_20of_20build_20profiles_44',['Creation of build profiles',['../md_crosscompiling.html#autotoc_md94',1,'']]],
  ['cross_20compilation_45',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['cross_20compiling_46',['Cross-Compiling',['../md_crosscompiling.html',1,'']]]
];
