var searchData=
[
  ['callback_20resource_20safety_0',['Callback Resource Safety',['../md_usage.html#autotoc_md65',1,'']]],
  ['callbacks_20unregister_1',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['cleanup_2',['Automatic Cleanup',['../md_usage.html#autotoc_md61',1,'']]],
  ['cmake_20config_20and_20build_3',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['cmake_20fetchcontent_4',['CMake FetchContent',['../md_installation.html#install-cmake-fetchcontent',1,'']]],
  ['cmake_20fetchcontent_20simplest_5',['Option 2: CMake FetchContent (Simplest)',['../md_quick__start.html#autotoc_md13',1,'']]],
  ['cmake_20subdirectory_6',['CMake subdirectory',['../md_installation.html#install-cmake-subdirectory',1,'']]],
  ['cmake_20toolchain_20from_20conan_20profile_7',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['compensation_8',['Feedforward Terms (Brewing Compensation)',['../pid_tuning.html#autotoc_md78',1,'']]],
  ['compilation_9',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['compiling_10',['Cross-Compiling',['../md_crosscompiling.html',1,'']]],
  ['complete_20example_11',['Complete Example',['../device_config.html#autotoc_md54',1,'']]],
  ['component_20access_12',['OpenpressoCore &amp;amp; Component Access',['../md_usage.html#autotoc_md58',1,'']]],
  ['component_20access_3a_13',['Component Access:',['../classopenpresso_1_1interfaces_1_1_openpresso_core.html#autotoc_md2',1,'']]],
  ['component_20overview_14',['Component overview',['../device_config.html#autotoc_md36',1,'']]],
  ['components_15',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['components_20dependencies_3a_16',['Components dependencies:',['../structopenpresso_1_1_device_config.html#autotoc_md1',1,'']]],
  ['components_20map_17',['The Components Map',['../device_config.html#autotoc_md32',1,'']]],
  ['conan_20package_20preferred_18',['Conan package (preferred)',['../md_installation.html#install-with-conan',1,'']]],
  ['conan_20profile_19',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['conan_20recommended_20',['Option 1: Conan (Recommended)',['../md_quick__start.html#autotoc_md12',1,'']]],
  ['config_20and_20build_21',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['configuration_22',['Configuration',['../device_config.html',1,'Device Configuration'],['../device_config.html#autotoc_md52',1,'Watchdog Configuration']]],
  ['configuration_20parameters_23',['Configuration Parameters',['../pid_tuning.html#autotoc_md75',1,'Configuration Parameters'],['../md_flow__sensor__tuning.html#autotoc_md86',1,'Configuration Parameters']]],
  ['configure_20components_24',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['containers_25',['Using prebuilt containers',['../md_crosscompiling.html#autotoc_md96',1,'']]],
  ['controller_20architecture_26',['Controller Architecture',['../md_usage.html#autotoc_md70',1,'']]],
  ['controllers_27',['Controllers',['../device_config.html#autotoc_md41',1,'Controllers'],['../md_usage.html#autotoc_md69',1,'Controllers']]],
  ['controllers_20deactivation_20and_20sensors_20callbacks_20unregister_28',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['core_29',['2. Initialize Core',['../md_quick__start.html#autotoc_md17',1,'']]],
  ['core_20destruction_30',['Safe Core Destruction',['../md_usage.html#autotoc_md64',1,'']]],
  ['creation_20of_20build_20profiles_31',['Creation of build profiles',['../md_crosscompiling.html#autotoc_md94',1,'']]],
  ['cross_20compilation_32',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['cross_20compiling_33',['Cross-Compiling',['../md_crosscompiling.html',1,'']]]
];
