var hierarchy =
[
    [ "openpresso::AcZeroCrossSensorConfig", "structopenpresso_1_1_ac_zero_cross_sensor_config.html", null ],
    [ "openpresso::Ads1115PressureSensorConfig", "structopenpresso_1_1_ads1115_pressure_sensor_config.html", null ],
    [ "openpresso::BrewProfilerConfig", "structopenpresso_1_1_brew_profiler_config.html", null ],
    [ "openpresso::brew_step_targets::ConstantFlow", "structopenpresso_1_1brew__step__targets_1_1_constant_flow.html", null ],
    [ "openpresso::brew_step_targets::ConstantPressure", "structopenpresso_1_1brew__step__targets_1_1_constant_pressure.html", null ],
    [ "openpresso::interfaces::ControllerBase", "classopenpresso_1_1interfaces_1_1_controller_base.html", [
      [ "openpresso::interfaces::BrewProfiler", "classopenpresso_1_1interfaces_1_1_brew_profiler.html", null ],
      [ "openpresso::interfaces::FlowRateController", "classopenpresso_1_1interfaces_1_1_flow_rate_controller.html", null ],
      [ "openpresso::interfaces::LogicalOutput", "classopenpresso_1_1interfaces_1_1_logical_output.html", null ],
      [ "openpresso::interfaces::PressureController", "classopenpresso_1_1interfaces_1_1_pressure_controller.html", null ],
      [ "openpresso::interfaces::TemperatureController", "classopenpresso_1_1interfaces_1_1_temperature_controller.html", null ]
    ] ],
    [ "openpresso::DeviceConfig", "structopenpresso_1_1_device_config.html", null ],
    [ "openpresso::I2cAddr", "structopenpresso_1_1_i2c_addr.html", null ],
    [ "openpresso::IntegralFlowRateControllerConfig", "structopenpresso_1_1_integral_flow_rate_controller_config.html", null ],
    [ "openpresso::interfaces::LogicalInput", "classopenpresso_1_1interfaces_1_1_logical_input.html", null ],
    [ "openpresso::LogicalInputPinConfig", "structopenpresso_1_1_logical_input_pin_config.html", null ],
    [ "openpresso::LogicalOutputPinConfig", "structopenpresso_1_1_logical_output_pin_config.html", null ],
    [ "openpresso::Max31856TemperatureSensorConfig", "structopenpresso_1_1_max31856_temperature_sensor_config.html", null ],
    [ "openpresso::Max6675TemperatureSensorConfig", "structopenpresso_1_1_max6675_temperature_sensor_config.html", null ],
    [ "openpresso::Nau7802WeightSensorConfig", "structopenpresso_1_1_nau7802_weight_sensor_config.html", null ],
    [ "openpresso::brew_step_advence_conditions::Never", "structopenpresso_1_1brew__step__advence__conditions_1_1_never.html", null ],
    [ "openpresso::brew_step_advence_conditions::OnStepTime", "structopenpresso_1_1brew__step__advence__conditions_1_1_on_step_time.html", null ],
    [ "openpresso::brew_step_advence_conditions::OnTotalTime", "structopenpresso_1_1brew__step__advence__conditions_1_1_on_total_time.html", null ],
    [ "openpresso::brew_step_advence_conditions::OnWeight", "structopenpresso_1_1brew__step__advence__conditions_1_1_on_weight.html", null ],
    [ "openpresso::interfaces::OpenpressoCore", "classopenpresso_1_1interfaces_1_1_openpresso_core.html", null ],
    [ "openpresso::interfaces::PidControllerState", "classopenpresso_1_1interfaces_1_1_pid_controller_state.html", null ],
    [ "openpresso::PidSettings", "structopenpresso_1_1_pid_settings.html", null ],
    [ "openpresso::PinAddr", "structopenpresso_1_1_pin_addr.html", null ],
    [ "openpresso::interfaces::PressureSensor", "classopenpresso_1_1interfaces_1_1_pressure_sensor.html", null ],
    [ "openpresso::PulseControlledDeviceConfig", "structopenpresso_1_1_pulse_controlled_device_config.html", null ],
    [ "openpresso::PulsePowerControllerConfig", "structopenpresso_1_1_pulse_power_controller_config.html", null ],
    [ "openpresso::PulsePressureControllerConfig", "structopenpresso_1_1_pulse_pressure_controller_config.html", null ],
    [ "openpresso::SteamControllerConfig", "structopenpresso_1_1_steam_controller_config.html", null ],
    [ "openpresso::TemperaturePidControllerConfig", "structopenpresso_1_1_temperature_pid_controller_config.html", null ],
    [ "openpresso::interfaces::TemperatureSensor", "classopenpresso_1_1interfaces_1_1_temperature_sensor.html", null ],
    [ "openpresso::VirbroPumpFlowController", "structopenpresso_1_1_virbro_pump_flow_controller.html", null ],
    [ "openpresso::VirbroPumpFlowSensor", "structopenpresso_1_1_virbro_pump_flow_sensor.html", null ],
    [ "openpresso::VirtualWeightSensorConfig", "structopenpresso_1_1_virtual_weight_sensor_config.html", null ],
    [ "openpresso::WatchdogConfig", "structopenpresso_1_1_watchdog_config.html", null ],
    [ "openpresso::interfaces::WeightSensor", "classopenpresso_1_1interfaces_1_1_weight_sensor.html", null ]
];