var searchData=
[
  ['callback_20resource_20safety_0',['Callback Resource Safety',['../md_usage.html#autotoc_md65',1,'']]],
  ['callback_5fdescriptor_5ft_1',['callback_descriptor_t',['../namespacelibopenpresso.html#a34e67c718c9879e0cb7620f2c293ae64',1,'libopenpresso']]],
  ['callback_5ft_2',['callback_t',['../classlibopenpresso_1_1interfaces_1_1_brew_profiler.html#a8e85a7f3a19a8c2f693e5b70bbdddedd',1,'libopenpresso::interfaces::BrewProfiler::callback_t'],['../classlibopenpresso_1_1interfaces_1_1_logical_input.html#a4a502d31a83c09b4dfcefd8d916f09a1',1,'libopenpresso::interfaces::LogicalInput::callback_t'],['../classlibopenpresso_1_1interfaces_1_1_pressure_sensor.html#a30076b56c4d793994c9d8f3e87ec17b1',1,'libopenpresso::interfaces::PressureSensor::callback_t'],['../classlibopenpresso_1_1interfaces_1_1_temperature_sensor.html#ab5cf869cf5426427fd46109eb27cab71',1,'libopenpresso::interfaces::TemperatureSensor::callback_t'],['../classlibopenpresso_1_1interfaces_1_1_weight_sensor.html#a0e384e0bab1bf74572137f3c81927fff',1,'libopenpresso::interfaces::WeightSensor::callback_t']]],
  ['callbacks_20unregister_3',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['chip_4',['chip',['../structlibopenpresso_1_1_pin_addr.html#a16c214bb91fcfce30c924ffade697480',1,'libopenpresso::PinAddr']]],
  ['cleanup_5',['Automatic Cleanup',['../md_usage.html#autotoc_md61',1,'']]],
  ['cmake_20config_20and_20build_6',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['cmake_20fetchcontent_7',['CMake FetchContent',['../md_installation.html#install-cmake-fetchcontent',1,'']]],
  ['cmake_20fetchcontent_20simplest_8',['Option 2: CMake FetchContent (Simplest)',['../md_quick__start.html#autotoc_md13',1,'']]],
  ['cmake_20subdirectory_9',['CMake subdirectory',['../md_installation.html#install-cmake-subdirectory',1,'']]],
  ['cmake_20toolchain_20from_20conan_20profile_10',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['code_11',['code',['../classlibopenpresso_1_1_system_error.html#a5d68f3cace0a9c07ee92ba89262307a8',1,'libopenpresso::SystemError']]],
  ['compensation_12',['Feedforward Terms (Brewing Compensation)',['../pid_tuning.html#autotoc_md78',1,'']]],
  ['compilation_13',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['compiling_14',['Cross-Compiling',['../md_crosscompiling.html',1,'']]],
  ['complete_20example_15',['Complete Example',['../device_config.html#autotoc_md54',1,'']]],
  ['component_20access_16',['LibopenpressoCore &amp;amp; Component Access',['../md_usage.html#autotoc_md58',1,'']]],
  ['component_20access_3a_17',['Component Access:',['../classlibopenpresso_1_1interfaces_1_1_libopenpresso_core.html#autotoc_md2',1,'']]],
  ['component_20overview_18',['Component overview',['../device_config.html#autotoc_md36',1,'']]],
  ['component_5fconfig_2ehpp_19',['component_config.hpp',['../component__config_8hpp.html',1,'']]],
  ['component_5fconfig_5ft_20',['component_config_t',['../namespacelibopenpresso.html#a372777f9e418d04c4e3e3b2973fd35f4',1,'libopenpresso']]],
  ['component_5flabel_5ft_21',['component_label_t',['../namespacelibopenpresso.html#ae2f9204b381602762a1266d2c344d6d4',1,'libopenpresso']]],
  ['components_22',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['components_23',['components',['../structlibopenpresso_1_1_device_config.html#aea434a18baabaf8c080cee3b795a83e3',1,'libopenpresso::DeviceConfig']]],
  ['components_20dependencies_3a_24',['Components dependencies:',['../structlibopenpresso_1_1_device_config.html#autotoc_md1',1,'']]],
  ['components_20map_25',['The Components Map',['../device_config.html#autotoc_md32',1,'']]],
  ['components_5fmap_5ft_26',['components_map_t',['../namespacelibopenpresso.html#a78fd7c6eb8c6b250542f10104a74d3ae',1,'libopenpresso']]],
  ['conan_20package_20preferred_27',['Conan package (preferred)',['../md_installation.html#install-with-conan',1,'']]],
  ['conan_20profile_28',['Generation of CMake Toolchain from conan profile',['../md_crosscompiling.html#cross-compiling-conan-install-step',1,'']]],
  ['conan_20recommended_29',['Option 1: Conan (Recommended)',['../md_quick__start.html#autotoc_md12',1,'']]],
  ['config_20and_20build_30',['Run CMake config and build',['../md_crosscompiling.html#autotoc_md95',1,'']]],
  ['config_2ehpp_31',['config.hpp',['../config_8hpp.html',1,'']]],
  ['configuration_32',['Configuration',['../device_config.html',1,'Device Configuration'],['../device_config.html#autotoc_md52',1,'Watchdog Configuration']]],
  ['configuration_20parameters_33',['Configuration Parameters',['../pid_tuning.html#autotoc_md75',1,'Configuration Parameters'],['../md_flow__sensor__tuning.html#autotoc_md86',1,'Configuration Parameters']]],
  ['configure_20components_34',['1. Configure Components',['../md_quick__start.html#autotoc_md16',1,'']]],
  ['constantflow_35',['ConstantFlow',['../structlibopenpresso_1_1brew__step__targets_1_1_constant_flow.html',1,'libopenpresso::brew_step_targets']]],
  ['constantpressure_36',['ConstantPressure',['../structlibopenpresso_1_1brew__step__targets_1_1_constant_pressure.html',1,'libopenpresso::brew_step_targets']]],
  ['containers_37',['Using prebuilt containers',['../md_crosscompiling.html#autotoc_md96',1,'']]],
  ['controller_20architecture_38',['Controller Architecture',['../md_usage.html#autotoc_md70',1,'']]],
  ['controller_5fbase_2ehpp_39',['controller_base.hpp',['../controller__base_8hpp.html',1,'']]],
  ['controllerbase_40',['ControllerBase',['../classlibopenpresso_1_1interfaces_1_1_controller_base.html',1,'libopenpresso::interfaces']]],
  ['controllerbaseptr_41',['ControllerBasePtr',['../namespacelibopenpresso.html#ac4807f0dae3e30ccb73cd7c6c9cbfba8',1,'libopenpresso']]],
  ['controllers_42',['Controllers',['../device_config.html#autotoc_md41',1,'Controllers'],['../md_usage.html#autotoc_md69',1,'Controllers']]],
  ['controllers_20deactivation_20and_20sensors_20callbacks_20unregister_43',['Controllers deactivation and sensors callbacks unregister',['../md_usage.html#autotoc_md62',1,'']]],
  ['core_44',['2. Initialize Core',['../md_quick__start.html#autotoc_md17',1,'']]],
  ['core_20destruction_45',['Safe Core Destruction',['../md_usage.html#autotoc_md64',1,'']]],
  ['coreptr_46',['CorePtr',['../namespacelibopenpresso.html#a948ec0092f3b4c7840f74e4cee86be74',1,'libopenpresso']]],
  ['creation_20of_20build_20profiles_47',['Creation of build profiles',['../md_crosscompiling.html#autotoc_md94',1,'']]],
  ['cross_20compilation_48',['Build environment for cross compilation',['../md_crosscompiling.html#autotoc_md93',1,'']]],
  ['cross_20compiling_49',['Cross-Compiling',['../md_crosscompiling.html',1,'']]]
];
